config/routes.rb
Rails.application.routes.draw do
  resources :reports
  root 'reports#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
    has_one_attached :image_a#, prefix: 'report'
    has_one_attached :image_b#, prefix: 'report'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout 'home'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  require 'aws-sdk'

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    Aws.config.update({
      credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'])
    })
    
    client = Aws::Rekognition::Client.new(
      region: ENV['AWS_REGION'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
    )
    
    

    @text_detections_a = client.detect_text({
      image: { # required
        s3_object: {
          bucket: ENV['AWS_BUCKET'],
          name: @report.image_a.key          
        }
      }      
    })

    @text_detections_b = client.detect_text({
      image: { # required
        s3_object: {
          bucket: ENV['AWS_BUCKET'],
          name: @report.image_b.key          
        }
      }      
    })

    @detect_labels_a = client.detect_labels({
      image: { # required
        s3_object: {
          bucket: ENV['AWS_BUCKET'],
          name: @report.image_a.key          
        }
      }   
    })

    @detect_labels_b = client.detect_labels({
      image: { # required
        s3_object: {
          bucket: ENV['AWS_BUCKET'],
          name: @report.image_b.key          
        }
      }     
    })


    @detect_moderation_labels_a = client.detect_moderation_labels({
      image: { # required
        s3_object: {
          bucket: ENV['AWS_BUCKET'],
          name: @report.image_a.key
        },
      },
      min_confidence: 1.0,
    })

    @detect_moderation_labels_b = client.detect_moderation_labels({
      image: { # required
        s3_object: {
          bucket: ENV['AWS_BUCKET'],
          name: @report.image_b.key
        },
      },
      min_confidence: 1.0,
    })
    
    
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :image_a, :image_b)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>TribuRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

      <div class="container-fluid">
          <div class="container">
              <p id="notice"><%= notice %></p>
              <%= yield %>    
          </div> 
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="Segundo España">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <title>Dashboard CarGarpp</title>
  <%= render 'layouts/render/css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="animsition site-navbar-small dashboard">
  <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

  <!--NAV-->
  <!-- AJUSTAR NOTIFICACIONES, TRADUCION DE IDIOMA Y INFORMACION DEL USUARIO-->  
  

 
  <!-- Page -->
  <div class="page">
    <div class="page-content container-fluid">
      
      <!--ALERT-->
      <% if notice %>
        <div class="alert alert-success" id="examplebtTableEventsResult" role="alert">
            <p id="notice"><%= notice %></p>
        </div>
      <% end %>
      <%= yield %>

    </div>
  </div>
  <!-- End Page -->

  <!--MODALS-->
  

  <!-- Footer -->
  

  <!--JS-->
  <%= render 'layouts/render/js' %>

</body>



</html>

app/views/layouts/render/_css.html.erb
    <link rel="apple-touch-icon" href="/admin-admin-assets/images/apple-touch-icon.png">
    <link rel="shortcut icon" href="/admin-assets/images/favicon.ico">
    
    <!-- Stylesheets -->
    <link rel="stylesheet" href="/global/css/bootstrap.min.css">
    <link rel="stylesheet" href="/global/css/bootstrap-extend.min.css">
    <link rel="stylesheet" href="/admin-assets/css/site.min.css">
    
    <!-- Plugins -->
    <link rel="stylesheet" href="/global/vendor/animsition/animsition.css">
    <link rel="stylesheet" href="/global/vendor/asscrollable/asScrollable.css">
    <link rel="stylesheet" href="/global/vendor/switchery/switchery.css">
    <link rel="stylesheet" href="/global/vendor/intro-js/introjs.css">
    <link rel="stylesheet" href="/global/vendor/slidepanel/slidePanel.css">
    <link rel="stylesheet" href="/global/vendor/flag-icon-css/flag-icon.css">
        <link rel="stylesheet" href="/global/vendor/chartist/chartist.css">
        <link rel="stylesheet" href="/global/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css">
        <link rel="stylesheet" href="/global/vendor/aspieprogress/asPieProgress.css">
        <link rel="stylesheet" href="/global/vendor/jquery-selective/jquery-selective.css">
        <link rel="stylesheet" href="/global/vendor/bootstrap-datepicker/bootstrap-datepicker.css">
        <link rel="stylesheet" href="/global/vendor/asscrollable/asScrollable.css">
        <link rel="stylesheet" href="/admin-assets/examples/css/dashboard/team.css">
    
    
    <!-- Fonts -->
    <link rel="stylesheet" href="/global/fonts/web-icons/web-icons.min.css">
    <link rel="stylesheet" href="/global/fonts/brand-icons/brand-icons.min.css">
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

    <link rel="stylesheet" href="/admin-assets/examples/css/pages/register-v3.css">
    
    <!--[if lt IE 9]>
    <script src="/global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
    
    <!--[if lt IE 10]>
    <script src="/global/vendor/media-match/media.match.min.js"></script>
    <script src="/global/vendor/respond/respond.min.js"></script>
    <![endif]-->
    
    <!-- Scripts -->
    <script src="/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>

app/views/layouts/render/_footer.html.erb
<!-- Footer -->
<footer class="site-footer">
    <div class="site-footer-legal">© 2019 <a
            href="https://www.cargapp.co">CarGapp</a></div>
    <div class="site-footer-right">
        Creado <i class="red-600 wb wb-heart"></i> por <a
            href="https://www.ideardev.com"> IdearDev</a>
    </div>
</footer>

app/views/layouts/render/_js.html.erb
<!-- Core  -->
  <script src="/global/vendor/babel-external-helpers/babel-external-helpers.js"></script>
  <script src="/global/vendor/jquery/jquery.js"></script>
  <script src="/global/vendor/popper-js/umd/popper.min.js"></script>
  <script src="/global/vendor/bootstrap/bootstrap.js"></script>
  <script src="/global/vendor/animsition/animsition.js"></script>
  <script src="/global/vendor/mousewheel/jquery.mousewheel.js"></script>
  <script src="/global/vendor/asscrollbar/jquery-asScrollbar.js"></script>
  <script src="/global/vendor/asscrollable/jquery-asScrollable.js"></script>

  <!-- Plugins -->
  <script src="/global/vendor/switchery/switchery.js"></script>
  <script src="/global/vendor/intro-js/intro.js"></script>
  <script src="/global/vendor/screenfull/screenfull.js"></script>
  <script src="/global/vendor/slidepanel/jquery-slidePanel.js"></script>
  <script src="/global/vendor/chartist/chartist.js"></script>
  <script src="/global/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.js"></script>
  <script src="/global/vendor/aspieprogress/jquery-asPieProgress.js"></script>
  <script src="/global/vendor/matchheight/jquery.matchHeight-min.js"></script>
  <script src="/global/vendor/jquery-selective/jquery-selective.min.js"></script>
  <script src="/global/vendor/bootstrap-datepicker/bootstrap-datepicker.js"></script>

  <!-- Scripts -->
  <script src="/global/js/Component.js"></script>
  <script src="/global/js/Plugin.js"></script>
  <script src="/global/js/Base.js"></script>
  <script src="/global/js/Config.js"></script>

  <script src="/admin-assets/js/Section/Menubar.js"></script>
  <script src="/admin-assets/js/Section/Sidebar.js"></script>
  <script src="/admin-assets/js/Section/PageAside.js"></script>
  <script src="/admin-assets/js/Plugin/menu.js"></script>

  <!-- Config -->
  <script src="/global/js/config/colors.js"></script>
  <script src="/admin-assets/js/config/tour.js"></script>
  <script>Config.set('admin-assets', '/admin-assets');</script>

  <!-- Page -->
  <script src="/admin-assets/js/Site.js"></script>
  <script src="/global/js/Plugin/asscrollable.js"></script>
  <script src="/global/js/Plugin/slidepanel.js"></script>
  <script src="/global/js/Plugin/switchery.js"></script>
  <script src="/global/js/Plugin/matchheight.js"></script>
  <script src="/global/js/Plugin/aspieprogress.js"></script>
  <script src="/global/js/Plugin/bootstrap-datepicker.js"></script>
  <script src="/global/js/Plugin/asscrollable.js"></script>

  <script src="/admin-assets/examples/js/dashboard/team.js"></script>

app/views/layouts/render/_menu.html.erb
<div class="site-menubar site-menubar-light">
    <div class="site-menubar-body">
      <div>
        <div>
          <ul class="site-menu" data-plugin="menu">
            <li class="site-menu-category">General CarGapp</li>

            <li class="dropdown site-menu-item has-sub">
              <%= link_to offers_path, class: 'animsition-link' do %>
                <i class="site-menu-icon wb-tag" aria-hidden="true"></i>
                <span class="site-menu-title">Offers</span>
              <% end %>
            </li>

            <li class="dropdown site-menu-item has-sub">
              <%= link_to reports_path, class: 'animsition-link' do %>
                <i class="site-menu-icon wb-flag" aria-hidden="true"></i>
                <span class="site-menu-title">Reports</span>
              <% end %>
            </li>

            <% if user_signed_in? %>
              <% if current_user.email.include?('segundo') or current_user.email.include?('segundo.espana1@gmail.com') %>
                <li class="dropdown site-menu-item has-sub">
                  <%= link_to oauth_applications_path, class: 'animsition-link' do %>
                    <i class="site-menu-icon wb-user-add" aria-hidden="true"></i>
                    <span class="site-menu-title">Applications</span>
                  <% end %>
                </li>

                <li class="dropdown site-menu-item has-sub">
                  <%= link_to rails_admin_path, class: 'animsition-link' do %>
                    <i class="site-menu-icon wb-users" aria-hidden="true"></i>
                    <span class="site-menu-title">SuperAdmin</span>
                  <% end %>
                </li>
              <% end %>
            <% end %>
            
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/render/_modals.html.erb
<!-- Add Item Dialog -->
  <div id="addtodoItemForm" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="addtodoItemForm"
    aria-hidden="true">
    <div class="modal-dialog modal-simple">
      <form class="modal-content form-horizontal" role="form" action="#" method="post">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="moadl-title">Create New To Do Item</h4>
        </div>
        <div class="modal-body">
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="title">Title:</label>
            <div class="col-sm-10">
              <input id="title" class="form-control" type="text" name="title" />
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="dueDate">Due Date</label>
            <div class="col-sm-10">
              <div class="input-group">
                <input id="dueDate" class="form-control" type="text" data-plugin="datepicker"
                  data-container="#addtodoItemForm" />
                <span class="input-group-append">
                  <i class="icon wb-calendar" aria-hidden="true"></i>
                </span>
              </div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="people">People:</label>
            <div class="col-sm-10">
              <select id="people" multiple="multiple" class="plugin-selective">
              </select>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="form-actions">
            <button class="btn btn-primary" data-dismiss="modal" type="button">
              Add This Item
            </button>
            <a class="btn btn-sm btn-white" data-dismiss="modal" href="javascript:void(0)">
              Cancel
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- End Add Item Dialog -->

  <!-- Edit Dialog -->
  <div class="modal fade" id="edittodoItemForm" aria-hidden="true" aria-labelledby="edittodoItemForm" role="dialog"
    tabindex="-1" data-show="false">
    <div class="modal-dialog modal-simple">
      <form class="modal-content form-horizontal" action="#" method="post" role="form">
        <div class="modal-header">
          <button type="button" class="close" aria-hidden="true" data-dismiss="modal">×</button>
          <h4 class="modal-title">Edit To Do Item</h4>
        </div>
        <div class="modal-body">
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="editTitle">Title:
            </label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="editTitle" name="editTitle">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="editStarts">Due Date:
            </label>
            <div class="col-sm-10">
              <div class="input-group">
                <input type="text" class="form-control" id="editDueDate" name="editDueDate"
                  data-container="#edittodoItemForm" data-plugin="datepicker">
                <span class="input-group-append">
                  <i class="icon wb-calendar" aria-hidden="true"></i>
                </span>
              </div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="editPeople">People:
            </label>
            <div class="col-sm-10">
              <select id="editPeople" multiple="multiple" class="plugin-selective"></select>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="form-actions">
            <button class="btn btn-primary" data-dismiss="modal" type="button">Save</button>
            <button class="btn btn-danger" data-dismiss="modal" type="button">Delete</button>
            <a class="btn btn-sm btn-white" data-dismiss="modal" href="javascript:void(0)">Cancel</a>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- End Edit Dialog -->

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image_a %>
    <%= form.file_field :image_a %>
  </div>

  <div class="field">
    <%= form.label :image_b %>
    <%= form.file_field :image_b %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image a</th>
      <th>Image b</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.name %></td>
        <td><%= report.image_a %></td>
        <td><%= report.image_b %></td>
        <td><%= link_to 'Show', report, class: 'btn btn-primary  animsition-link' %></td>
        <td><%= link_to 'Edit', edit_report_path(report), class: 'btn btn-primary my-2 animsition-link' %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary my-2 animsition-link' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<div class="panel">
  <div class="panel-body container-fluid">

    <!-- Card -->
    <div class="card-group">
      <div class="card card-block p-0">
        <div class="counter counter-md vertical-align bg-blue-700 h-300">

            <img class="cover-image"src="<%= @report.image_a.attached? ? url_for(@report.image_a) : '/report/images/single/1.jpg' %>" style='height:20vw;width:35vw;margin-bottom:1px;'>
          
        </div>

        
        <% @text_detections_a.text_detections.each do |text| %>
          <%= text.detected_text %>
        <% end %>                                             
        
        <hr>

        <% @detect_labels_a.labels.each do |label| %>
          <%= label.name %> - <%= label.confidence %><br>
        <% end %>

        <hr>

        <% @detect_moderation_labels_a.moderation_labels.each do |moderation| %>
          <%= moderation.parent_name %> - <%= moderation.name %> - <%= moderation.confidence %><br>
        <% end %>

      </div>
      <div class="card card-block p-0">
        <div class="counter counter-md vertical-align bg-red-700 h-300">          
            
          <img class="cover-image" src="<%= @report.image_b.attached? ? url_for(@report.image_b) : '/report/images/single/1.jpg' %>" style='height:20vw;width:35vw;margin-bottom:1px;'>

        </div>

          <% @text_detections_b.text_detections.each do |text| %>
            <%= text.detected_text %>
          <% end %>
          
          <hr>

          <% @detect_labels_b.labels.each do |label| %>
            <%= label.name %> - <%= label.confidence %><br>
          <% end %>

          <hr>

          <% @detect_moderation_labels_b.moderation_labels.each do |moderation| %>
            <%= moderation.parent_name %> - <%= moderation.name %> - <%= moderation.confidence %><br>
          <% end %>

      </div>
    </div>
    <!-- End Card -->

  </div>
</div>

<center>
  <%= link_to 'Edit', edit_report_path(@report), class: 'btn btn-primary my-2 animsition-link' %>
  <%= link_to 'Back', reports_path, class: 'btn btn-primary my-2 animsition-link' %>
</center>